### ISSUE TITLE
Padding Between Buttons

### ISSUE THREAD

**Issue by RonakAggarwal** [Skill-Class/Tap-The-Unique#11]
The game screen contains so many buttons each representing a number. The spacing between buttons is hardcoded as of now. We want this spacing to be adjusted from end to end according to different screen sizes for a better look.

**Comment by beccadaniel** [comment]
I'll like to pick up this issue, do I go ahead?

**Comment by RonakAggarwal** [comment]
Hey @beccadaniel
That would be really great. I am assigning this issue to you.
Best of luck!

**Comment by theGeekyLad** [comment]
Hey @RonakAggarwal , check out this PR [here](https://github.com/Skill-Class/Tap-The-Unique/pull/17) that fixes horizontal button alignment. Never knew I had to post it up here before starting work on it. You're free to discard it since it's already assigned to another dev. :-)

**Comment by RonakAggarwal** [comment]
Hey @theGeekyLad 
Thanks for your efforts.
@beccadaniel You can also come up with your solutions as there is always a chance of improvement.

**Comment by beccadaniel** [comment]
@RonakAggarwal, I have a PR ready to this effect. Thanks
