### ISSUE TITLE
Animation within game screen

### ISSUE THREAD

**Issue by RonakAggarwal** [Skill-Class/Tap-The-Unique#12]
Tap-The-Unique game requires the change of numbers after every attempt by user. As of now, numbers are changing simply, We want something that catches the user attention. Creative ideas would be welcomed.

**For example:** whenever user clicks on a number, the next buttons appear in some animated way such as previous buttons goes into the screen and new buttons come out of it. This is just an example, there could be so many different ways of doing it.

**Comment by beccadaniel** [comment]
I want to work on this. Do I go ahead?

**Comment by ksheetal** [comment]
Yeah, sure.
All the best.
