### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by ksheetal** [Skill-Class/Tap-The-Unique#3]

**Comment by abkoradiya** [comment]
I want to contribute this. Which type of splash screen needed?

**Comment by ksheetal** [comment]
Hello @abkoradiya,
Thanks for taking interest in this issue. here is a little description of the game.

> This is a simple game that tests the concentration of the child based on how he or she is able to select a unique number out of all other numbers.

You are free to use any design you want  as of now. I am assigning this issue to you.
All the best.!

**Comment by abkoradiya** [comment]
Can you reference design? as I am not a designer, so I can't think like designer.

**Comment by ksheetal** [comment]
Hi, in README.md you can see there is an intro activity. If you can put some animations in that it would also work!

**Comment by deytulsi18** [comment]
Hey I have made a Splash Screen.
Please assign it to me.
