### ISSUE TITLE
Add a proper read me file.

### ISSUE THREAD

**Issue by ksheetal** [Skill-Class/Tap-The-Unique#4]

**Comment by diamondlee7** [comment]
@ksheetal I can pick up this issue. Do you just want a blank read me file? If not what would you like included in the readMe file? Please assign this issue to me.

**Comment by ksheetal** [comment]
Hello @diamondlee7,
Thanks for taking interest in this issue. here is a little description of the game.

> This is a simple game that tests the concentration of the child based on how he or she is able to select a unique number out of all other numbers.

We want something like this. [https://github.com/Skill-Class/TicTacToeGame/blob/master/README.md]()

I am assigning this issue to you.

All the best.!

**Comment by ksheetal** [comment]
Hi, any updates?

**Comment by UshasriMavuri1999** [comment]
Hey @ksheetal , I would like to work on this:)
Can you please assign this to me?

**Comment by ksheetal** [comment]
Hi @UshasriMavuri1999 
Thanks for taking interest in this issue. 

Before writing the README.md please clone and run the build once for better understanding of the project.

We want something like this.
[https://github.com/Skill-Class/TicTacToeGame/blob/master/README.md](url)

For any help, you can comment here.

Thank you and all the very best :)

**Comment by UshasriMavuri1999** [comment]
Hey @ksheetal, I made a pr
Can you please verify that.....and please mention if you need any changes to it



One thing to add on... I got an ineligible tag for this pr.... it might be not adding "hacktoberfest" label to this repo.
![screencapture-hacktoberfest-digitalocean-profile-2020-10-03-19_22_04](https://user-images.githubusercontent.com/49982556/94993390-55fca080-05ae-11eb-9c3f-27b825a5f94c.png)

**Comment by ksheetal** [comment]
Hi @UshasriMavuri1999 
Really good PR. There is a small correction that I have mentioned. Please check that.
Also, I have added the label. :)
Thanks
